apiVersion: v2
appVersion: "1.0"
description: A Helm chart for aaa-jjj App
name: aaa-jjj
home: https://github.com/hmcts/aaa-jjj
version: 0.0.1
maintainers:
  - name: HMCTS aaa team
dependencies:
  - name: java
    version: 3.0.2
    repository: '@hmctspublic'
